# Generated by Django 5.0.6 on 2024-06-21 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=255)),
                ('plec', models.CharField(max_length=255)),
                ('kolor', models.CharField(max_length=255)),
                ('siersc', models.CharField(max_length=255)),
                ('rasa', models.CharField(max_length=255)),
                ('wiek', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ogloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField()),
                ('data', models.DateTimeField()),
                ('kot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kot')),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('ogloszenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ogloszenie')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres_1', models.CharField(blank=True, max_length=255)),
                ('adres_2', models.CharField(blank=True, max_length=255)),
                ('nr_tel', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zdjecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dane', models.ImageField(upload_to='zdjecia/')),
                ('ogloszenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ogloszenie')),
            ],
        ),
    ]
