# Generated by Django 5.0.6 on 2024-06-24 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_rezerwacja_uzytkownik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerwacja',
            name='ogloszenie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.ogloszenie'),
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='uzytkownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
