# Generated by Django 5.0.6 on 2024-06-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_rezerwacja_ogloszenie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogloszenie',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zdjecie',
            name='dane',
            field=models.ImageField(upload_to=''),
        ),
    ]
